name: parse-sec-filings
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.8.16
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - aiohttp==3.7.4.post0
    - async-timeout==3.0.1
    - attrs==22.2.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.11.2
    - bs4==0.0.1
    - chardet==4.0.0
    - charset-normalizer==3.0.1
    - courlan==0.8.3
    - dateparser==1.1.7
    - docopt==0.6.2
    - htmldate==1.4.1
    - idna==3.4
    - justext==3.0.0
    - langcodes==3.3.0
    - lxml==4.9.2
    - multidict==6.0.4
    - pipreqs==0.4.11
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - pytz-deprecation-shim==0.1.0.post0
    - regex==2022.10.31
    - requests==2.28.2
    - secedgar==0.5.0
    - six==1.16.0
    - soupsieve==2.4
    - tld==0.12.7
    - tqdm==4.64.1
    - trafilatura==1.4.1
    - typing-extensions==4.5.0
    - tzdata==2022.7
    - tzlocal==4.2
    - urllib3==1.26.14
    - yarg==0.1.9
    - yarl==1.8.2
